config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :blogs do
    member do
      put 'publish'
    end
  end
  get  'home/index'
  get  'profiles/oauth/github',
       to: 'profiles/oauth_github#oauth_initiate'
  get  'profiles/oauth/github/callback',
       to: 'profiles/oauth_github#oauth_callback'

  post 'internal/api/initial_analysis',
       to: 'analysis_endpoints/receive_analysis#receive_initial_analysis'
  post 'internal/api/tech_analysis',
       to: 'analysis_endpoints/receive_analysis#add_tech_analysis_by_repo'
  post 'internal/api/tech_analysis/status',
       to: 'analysis_endpoints/receive_analysis#tech_analysis_status'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    invitations: 'users/invitations',
    registrations: 'users/registrations'
  }, skip: [:registrations]

  as :user do
    put 'users' => 'users/registrations#update', :as => 'user_registration'
    delete 'users' => 'users/registrations#destroy', :as => 'user_delete'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  # Each step is further described in the setup controller
  scope '/setup' do
    get '/', to: 'setup#index', as: 'setup'
    get '/1', to: 'setup#step_one', as: 'setup_step_one'
    get '/2', to: 'setup#step_two', as: 'setup_step_two'
    get '/3', to: 'setup#step_three', as: 'setup_step_three'
    get '/4', to: 'setup#step_four', as: 'setup_step_four'

    post '/1', to: 'setup#step_one_submit', as: 'setup_step_one_submit'
    post '/2', to: 'setup#step_two_submit', as: 'setup_step_two_submit'
    post '/3', to: 'setup#step_three_submit', as: 'setup_step_three_submit'
    post '/4', to: 'setup#step_four_submit', as: 'setup_step_four_submit'

    post '/previous_step', to: 'setup#previous_step', as: 'setup_previous_step'
  end

  scope '/internal/api' do
    post 'initial_analysis',
         to: 'analysis_endpoints/receive_analysis#receive_initial_analysis'
    post 'tech_analysis',
         to: 'analysis_endpoints/receive_analysis#add_tech_analysis_by_repo'
    post 'repo_analysis',
         to: 'analysis_endpoints/receive_analysis#repo_analysis'
  end

  scope '/data_api' do
    get '/user_info', to: 'data_api#user_info'
    get '/user_socials', to: 'data_api#user_socials'
    get '/projects', to: 'data_api#projects'
    get '/projects/:id', to: 'data_api#project_info'
    get '/projects/:project_id/repos/:repo_id', to: 'data_api#project_repo'
    get '/blogs', to: 'data_api#blogs'
    get '/blogs/:id', to: 'data_api#blog_info'
  end

  scope '/settings' do
    get '/profile', to: 'settings#profile'
    put '/profile', to: 'settings#profile_edit'
    put '/profile_social', to: 'settings#social_edit'
    put '/profile_contact_info', to: 'settings#contact_info_edit'
    get '/themes', to: 'settings#themes'
    put '/themes', to: 'settings#themes_edit'
    get '/account', to: 'settings#account'
    get '/password', to: 'settings#password'
  end

  scope '/projects' do
    get '/', to: 'projects#index', as: 'projects_home'
    get '/new', to: 'projects#new', as: 'project_new'
    put '/new', to: 'projects#create', as: 'project_create'
    get '/:id', to: 'projects#show', as: 'project'
    put '/:id', to: 'projects#update', as: 'update_project'
    get '/:id/edit', to: 'projects#edit', as: 'edit_project'
    delete '/:id', to: 'projects#delete', as: 'delete_project'
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  layout 'settings'
  def profile
    @profile = current_user.profile
    @base_social_links = Profile.base_social_links
    @social_links = current_user.profile.social_links.symbolize_keys
    @contact_info = current_user.profile.contact_info
    @user = current_user
  end

  def account; end

  def themes
    @valid_themes = Profile.valid_themes
    @current_theme = current_user.profile.theme
  end

  def password; end

  def profile_edit
    user = User.find(current_user.id)

    params_object = profile_params

    avatar = params_object.delete(:avatar)
    unless avatar.nil?
      begin
        response = Cloudinary::Uploader.upload(avatar.to_io,
                                               folder: 'user_avatars/',
                                               public_id: current_user.id,
                                               width: 256,
                                               height: 256,
                                               gravity: 'face',
                                               crop: 'thumb')
      rescue CloudinaryException => e
        redirect_to profile_path,
                    alert: e.message
        return
      end
      params_object[:avatar_url] = response.fetch('url')
    end

    if user.update(params_object)
      redirect_to profile_path,
                  notice: 'Updated Successfully'
    else
      redirect_to profile_path,
                  alert: 'Something went wrong. Please try again.'
    end
  end

  def social_edit
    profile = current_user.profile

    if profile.update(social_params)
      redirect_to profile_path,
                  notice: 'Updated Successfully'
    else
      redirect_to profile_path,
                  alert: 'Something went wrong. Please try again.'
    end
  end

  def themes_edit
    profile = current_user.profile
    theme = Theme.find(theme_params[:theme])
    if profile.update(theme: theme)
      profile.start_theme_build
      redirect_to themes_path,
                  notice: 'Theme updated successfully! Your new portfolio' \
                          ' will be up in a few minutes'
    else
      redirect_to themes_path,
                  alert: profile.errors.full_messages.to_sentence
    end
  end

  def contact_info_edit
    profile = current_user.profile

    params_object = contact_info_params

    if params_object.dig('contact_info', 'phone')
      phone = Phonelib.parse(params_object.dig('contact_info', 'phone'))
      params_object[:contact_info][:phone] =
        if phone.country_code
          phone.international
        else
          phone.e164
        end
    end

    if profile.update(params_object)
      redirect_to profile_path, notice: 'Updated successfully!'
    else
      redirect_to profile_path, alert: profile.errors.full_messages.to_sentence
    end
  end

  private

  def profile_params
    params.require(:user).permit(:first_name, :last_name, :avatar)
  end

  def contact_info_params
    params.require(:profile).permit(contact_info: %i[email phone location])
  end

  def social_params
    params.require(:profile).permit(:tagline,
                                    social_links: Profile.valid_socials)
  end

  def theme_params
    params.require(:theme).permit(:theme)
  end

  def resource_name
    :user
  end
  helper_method :resource_name

  def resource
    @resource ||= User.new
  end
  helper_method :resource

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  helper_method :devise_mapping

  def resource_class
    User
  end
  helper_method :resource_class
end

app/views/settings/account.html.erb
<div>
  <h2 class="text-xl leading-6 font-medium text-gray-900">Account</h2>
  <p class="mt-1 text-sm text-gray-500">
    GitHub is all we got for logging in for now. But do request us if you want some more ways :)
  </p>
</div>
<div class="relative mt-3">
  <div class="absolute inset-0 flex items-center" aria-hidden="true">
    <div class="w-full border-t border-gray-300"></div>
  </div>
</div>
<div class="mt-10">
  <div class="flex items-center shadow border rounded p-5">
    <div class="pr-3">
      <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full">
        <svg class="w-8 h-8 mr-2" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 0C4.477 0 0 4.484 0 10.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0110 4.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.203 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.942.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0020 10.017C20 4.484 15.522 0 10 0z" clip-rule="evenodd" />
        </svg>
      </div>
    </div>
    <div>
      <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-headline">
        Login Easily with GitHub
      </h3>
      <div class="mt-2">
        <p class="text-sm text-gray-500">
          <% if current_user.provider == nil %>
            If you still haven't connected your GitHub for authentication, what are you waiting for? This is the perfect chance. You can login to Hyperlog with single click! How cool right?
          <% else%>
            You seem to have done this step already. You can tinker around in other places I suppose.
          <% end %>
        </p>
      </div>
      <% if current_user.provider == nil %>
        <div class="mt-3">
          <div class="relative inline-flex rounded-md shadow-sm">
            <%= button_to user_github_omniauth_authorize_path, method: :post, form: {"data-turbo" => "false"}, class: "w-full inline-flex justify-center py-2 px-4 border border-gray-300 rounded-md shadow-sm bg-white text-sm font-medium text-gray-500 hover:bg-gray-50" do %>
              <span class="sr-only">Connect Github Auth</span>
              <svg class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                <path fill-rule="evenodd" d="M10 0C4.477 0 0 4.484 0 10.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0110 4.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.203 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.942.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0020 10.017C20 4.484 15.522 0 10 0z" clip-rule="evenodd" />
              </svg> Connect Github Auth
            <% end %>
          </div>
        </div>
      <% end%>
    </div>
  </div>
</div>

app/views/settings/login.html.erb
<div>
  <h2 class="text-xl leading-6 font-medium text-gray-900">Login Details</h2>
  <p class="mt-1 text-sm text-gray-500">
    Want to change the password? Or want to use GitHub for login? We got you covered.
  </p>
</div>
<div class="relative mt-3">
  <div class="absolute inset-0 flex items-center" aria-hidden="true">
    <div class="w-full border-t border-gray-300"></div>
  </div>
</div>
<div class="mt-10">
  <h3 class="text-lg text-gray-800 font-medium">Change Password</h3>
  <div class="flex flex-col lg:flex-row">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, class: "flex-grow space-y-4" }) do |f| %>
      <div class="field">
        <%= f.label :current_password, class:"block text-sm font-medium text-gray-700" %>
        <%= f.password_field :current_password, autocomplete: "current-password", class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm" %>
      </div>
      <div class="field">
        <%= f.label :password, "New Password", class:"block text-sm font-medium text-gray-700" %>
        <%= f.password_field :password, autocomplete: "new-password", class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm" %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation, class:"block text-sm font-medium text-gray-700" %>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm" %>
      </div>
      <%= f.submit "Update", class: "inline-flex items-center px-4 py-2 border border-transparent text-sm rounded-md shadow-sm text-white bg-teal-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500" %>
    <% end %>
  </div>
</div>

app/views/settings/password.html.erb
<div>
  <h2 class="text-xl leading-6 font-medium text-gray-900">Password</h2>
  <p class="mt-1 text-sm text-gray-500">
    This is required in the applications they say. I guess we could add afford to add it here.
  </p>
</div>
<div class="relative mt-3">
  <div class="absolute inset-0 flex items-center" aria-hidden="true">
    <div class="w-full border-t border-gray-300"></div>
  </div>
</div>
<div class="mt-10">
  <div class="flex flex-col lg:flex-row">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, class: "flex-grow space-y-5" }) do |f| %>
      <div class="w-1/2">
        <%= f.label :current_password, class:"block text-sm font-medium text-gray-700" %>
        <%= f.password_field :current_password, autocomplete: "current-password", class: "appearance-none mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm" %>
      </div>
      <div class="grid grid-cols-6 gap-6 mt-5">
        <div class="col-span-6 sm:col-span-3">
          <%= f.label :password, "New Password", class:"block text-sm font-medium text-gray-700" %>
          <%= f.password_field :password, autocomplete: "new-password", class: "mt-1 focus:ring-teal-500 focus:border-teal-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
        </div>
        <div class="col-span-6 sm:col-span-3">
          <%= f.label :password_confirmation, class:"block text-sm font-medium text-gray-700" %>
          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "mt-1 focus:ring-teal-500 focus:border-teal-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
        </div>
      </div>
      <%= f.submit "Update Password", class: "inline-flex items-center px-4 py-2 border border-transparent text-sm rounded-md shadow-sm text-white bg-teal-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500" %>
    <% end %>
  </div>
</div>

app/views/settings/profile.html.erb
<div>
  <h2 class="text-xl leading-6 font-medium text-gray-900">Profile</h2>
  <p class="mt-1 text-sm text-gray-500">
    These details go up on the account. So change them cautiously.
  </p>
</div>
<div class="relative mt-3">
  <div class="absolute inset-0 flex items-center" aria-hidden="true">
    <div class="w-full border-t border-gray-300"></div>
  </div>
</div>
<div class="mt-10">
  <h3 class="text-lg text-gray-800 font-medium">Primary Details</h3>
  <div class="flex flex-col lg:flex-row">
    <%= form_with model: @user, url: profile_path, html: { method: :put, class: "flex-grow space-y-4" } do |f| %>
      <div>
        <label for="username" class="block text-sm font-medium text-gray-700">
          Username
        </label>
        <div class="mt-1 rounded-md shadow-sm flex">
          <input type="text" name="username" id="username" autocomplete="username" disabled class="focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-l-md sm:text-sm border-gray-300 bg-gray-50" value="<%= current_user.username %>">
          <span class="bg-gray-50 border border-gray-300 rounded-r-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
            .hyperlog.dev
          </span>
        </div>
      </div>
      <div class="mt-6 grid grid-cols-12 gap-6">
        <div class="col-span-12 sm:col-span-6">
          <%= f.label :first_name, class: "block text-sm font-medium text-gray-700" %>
          <%= f.text_field :first_name, autocomplete: "given-name", class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm"%>
        </div>
        <div class="col-span-12 sm:col-span-6">
          <%= f.label :last_name, class: "block text-sm font-medium text-gray-700" %>
          <%= f.text_field :last_name, autocomplete: "family-name", class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm"%>
        </div>
      </div>
      <div class="sm:col-span-6">
        <%= f.label :avatar, class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1 flex items-center">
          <span class="h-12 w-12 rounded-full overflow-hidden bg-gray-100">
            <% if @user.avatar_url? %>
              <%= image_tag @user.avatar_url, id: "avatar_image" %>
            <% else %>
              <svg class="h-full w-full text-gray-300" fill="currentColor" viewBox="0 0 24 24">
                <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
              </svg>
            <% end %>
          </span>
          <label for="user_avatar" class="ml-5 bg-white py-2 px-3 border border-gray-300 rounded-md shadow-sm text-sm leading-4 font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 cursor-pointer">
            <span>Change</span>
            <%= f.file_field :avatar, accept: "image/*", class: "sr-only" %>
          </label>
        </div>
      </div>
      <%= f.submit "Update", class: "inline-flex items-center px-4 py-2 border border-transparent text-sm rounded-md shadow-sm text-white bg-teal-600 cursor-pointer hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500" %>
    <% end %>
  </div>
  <br />
  <h3 class="text-lg text-gray-800 font-medium">Social Profile</h3>
  <div class="flex flex-col lg:flex-row">
    <%= form_with model: @user.profile, url: profile_social_path, html: { method: :put, class: "flex-grow space-y-4" } do |f| %>
      <div class="bg-white">
        <div>
          <%= f.label :tagline, class: "block text-sm font-medium text-gray-700" %>
          <%= f.text_field :tagline, value: current_user.profile.tagline, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm"%>
        </div>
        <br />
        <div class="grid grid-cols-6 gap-6">
          <div class="col-span-6 sm:col-span-3">
            <%= f.label 'social_links[linkedin]', 'LinkedIn', class: "block text-sm font-medium text-gray-700" %>
            <div class="mt-1 flex rounded-md shadow-sm">
              <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
                <%= @base_social_links[:linkedin] %>
              </span>
              <%= f.text_field 'social_links[linkedin]', value: @social_links.fetch(:linkedin, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
            </div>
          </div>
          <div class="col-span-6 sm:col-span-3">
            <%= f.label 'social_links[devto]', 'Dev.to', class: "block text-sm font-medium text-gray-700" %>
            <div class="mt-1 flex rounded-md shadow-sm">
              <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
                <%= @base_social_links[:devto] %>
              </span>
              <%= f.text_field 'social_links[devto]', value: @social_links.fetch(:devto, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
            </div>
          </div>
          <div class="col-span-6 sm:col-span-3">
            <%= f.label 'social_links[stackoverflow]', 'Stack Overflow', class: "block text-sm font-medium text-gray-700" %>
            <div class="mt-1 flex rounded-md shadow-sm">
              <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
                <%= @base_social_links[:stackoverflow] %>
              </span>
              <%= f.text_field 'social_links[stackoverflow]', value: @social_links.fetch(:stackoverflow, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "User Number"%>
            </div>
          </div>
          <div class="col-span-6 sm:col-span-3">
            <%= f.label 'social_links[dribbble]', 'Dribbble', class: "block text-sm font-medium text-gray-700" %>
            <div class="mt-1 flex rounded-md shadow-sm">
              <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
                <%= @base_social_links[:dribbble] %>
              </span>
              <%= f.text_field 'social_links[dribbble]', value: @social_links.fetch(:dribbble, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
            </div>
          </div>
          <div class="col-span-6 sm:col-span-3">
            <%= f.label 'social_links[facebook]', 'Facebook', class: "block text-sm font-medium text-gray-700" %>
            <div class="mt-1 flex rounded-md shadow-sm">
              <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
                <%= @base_social_links[:facebook] %>
              </span>
              <%= f.text_field 'social_links[facebook]', value: @social_links.fetch(:facebook, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
            </div>
          </div>
          <div class="col-span-6 sm:col-span-3">
            <%= f.label 'social_links[twitter]', 'Twitter', class: "block text-sm font-medium text-gray-700" %>
            <div class="mt-1 flex rounded-md shadow-sm">
              <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
                <%= @base_social_links[:twitter] %>
              </span>
              <%= f.text_field 'social_links[twitter]', value: @social_links.fetch(:twitter, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
            </div>
          </div>
          <div class="col-span-6 sm:col-span-3">
            <%= f.label 'social_links[github]', 'GitHub', class: "block text-sm font-medium text-gray-700" %>
            <div class="mt-1 flex rounded-md shadow-sm">
              <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
                <%= @base_social_links[:github] %>
              </span>
              <%= f.text_field 'social_links[github]', value: @social_links.fetch(:github, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
            </div>
          </div>
        </div>
      </div>
      <%= f.submit "Update", class: "inline-flex items-center px-4 py-2 border border-transparent text-sm rounded-md shadow-sm text-white bg-teal-600 cursor-pointer hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500" %>
    <% end %>
  </div>
  <h3 class="text-lg text-gray-800 font-medium mt-10">Contact Info</h3>
  <div class="flex flex-col lg:flex-row">
    <%= form_with model: @user.profile, url: profile_contact_info_path, html: { method: :put, class: "flex-grow space-y-4" } do |f| %>
      <div class="mt-6 grid grid-cols-12 gap-6">
        <div class="col-span-12">
          <%= f.label 'contact_info[email]', 'Email Address', class: "block text-sm font-medium text-gray-700" %>
          <%= f.email_field 'contact_info[email]', value: @contact_info.fetch('email'), placeholder: 'yourname@example.com', class: "mt-1 block w-3/4 border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm" %>
        </div>
        <div class="col-span-12">
          <%= f.label 'contact_info[phone]', 'Phone Number', class: "block text-sm font-medium text-gray-700" %>
          <%= f.text_field 'contact_info[phone]', value: @contact_info.fetch('phone'), placeholder: 'Prefer adding your country code (e.g. +1 for US, +91 for India)', class: "mt-1 block w-3/4 border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm" %>
        </div>
        <div class="col-span-12">
          <%= f.label 'contact_info[location]', 'Location', class: "block text-sm font-medium text-gray-700" %>
          <%= f.text_field 'contact_info[location]', value: @contact_info.fetch('location'), placeholder: 'Geek City, Developer Heaven.', class: "mt-1 block w-3/4 border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm" %>
        </div>
      </div>
      <%= f.submit "Update", class: "inline-flex items-center px-4 py-2 border border-transparent text-sm rounded-md shadow-sm text-white bg-teal-600 cursor-pointer hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500" %>
    <% end %>
  </div>
</div>
<script>
  var avatar_input = document.getElementById('user_avatar');
  var avatar_image = document.getElementById('avatar_image');
  
  avatar_input.addEventListener('change', function(e){
    var file = this.files[0];
    var reader = new FileReader();
    reader.onload = function(){
      avatar_image.src = this.result;
    };
    reader.readAsDataURL(file);
  })
</script>