config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :blogs do
    member do
      put 'publish'
    end
  end
  get  'home/index'
  get  'profiles/oauth/github',
       to: 'profiles/oauth_github#oauth_initiate'
  get  'profiles/oauth/github/callback',
       to: 'profiles/oauth_github#oauth_callback'

  post 'internal/api/initial_analysis',
       to: 'analysis_endpoints/receive_analysis#receive_initial_analysis'
  post 'internal/api/tech_analysis',
       to: 'analysis_endpoints/receive_analysis#add_tech_analysis_by_repo'
  post 'internal/api/tech_analysis/status',
       to: 'analysis_endpoints/receive_analysis#tech_analysis_status'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    invitations: 'users/invitations',
    registrations: 'users/registrations'
  }, skip: [:registrations]

  as :user do
    put 'users' => 'users/registrations#update', :as => 'user_registration'
    delete 'users' => 'users/registrations#destroy', :as => 'user_delete'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  # Each step is further described in the setup controller
  scope '/setup' do
    get '/', to: 'setup#index', as: 'setup'
    get '/1', to: 'setup#step_one', as: 'setup_step_one'
    get '/2', to: 'setup#step_two', as: 'setup_step_two'
    get '/3', to: 'setup#step_three', as: 'setup_step_three'
    get '/4', to: 'setup#step_four', as: 'setup_step_four'

    post '/1', to: 'setup#step_one_submit', as: 'setup_step_one_submit'
    post '/2', to: 'setup#step_two_submit', as: 'setup_step_two_submit'
    post '/3', to: 'setup#step_three_submit', as: 'setup_step_three_submit'
    post '/4', to: 'setup#step_four_submit', as: 'setup_step_four_submit'

    post '/previous_step', to: 'setup#previous_step', as: 'setup_previous_step'
  end

  scope '/internal/api' do
    post 'initial_analysis',
         to: 'analysis_endpoints/receive_analysis#receive_initial_analysis'
    post 'tech_analysis',
         to: 'analysis_endpoints/receive_analysis#add_tech_analysis_by_repo'
    post 'repo_analysis',
         to: 'analysis_endpoints/receive_analysis#repo_analysis'
  end

  scope '/data_api' do
    get '/user_info', to: 'data_api#user_info'
    get '/user_socials', to: 'data_api#user_socials'
    get '/projects', to: 'data_api#projects'
    get '/projects/:id', to: 'data_api#project_info'
    get '/projects/:project_id/repos/:repo_id', to: 'data_api#project_repo'
    get '/blogs', to: 'data_api#blogs'
    get '/blogs/:id', to: 'data_api#blog_info'
  end

  scope '/settings' do
    get '/profile', to: 'settings#profile'
    put '/profile', to: 'settings#profile_edit'
    put '/profile_social', to: 'settings#social_edit'
    put '/profile_contact_info', to: 'settings#contact_info_edit'
    get '/themes', to: 'settings#themes'
    put '/themes', to: 'settings#themes_edit'
    get '/account', to: 'settings#account'
    get '/password', to: 'settings#password'
  end

  scope '/projects' do
    get '/', to: 'projects#index', as: 'projects_home'
    get '/new', to: 'projects#new', as: 'project_new'
    put '/new', to: 'projects#create', as: 'project_create'
    get '/:id', to: 'projects#show', as: 'project'
    put '/:id', to: 'projects#update', as: 'update_project'
    get '/:id/edit', to: 'projects#edit', as: 'edit_project'
    delete '/:id', to: 'projects#delete', as: 'delete_project'
  end
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :profile

  has_many :profile_repo_analyses, -> { distinct }, dependent: :nullify
  has_many :repos, -> { distinct }, through: :profile_repo_analyses

  validates :profile, presence: true
  validates :name, presence: true
  validates :tagline, presence: true

  validates_associated :profile

  validate :validate_number_of_repos
  validate :validate_analysis_profiles_must_match_project_profile

  after_initialize :set_defaults
  before_create do
    self.image_url ||= if repos.length.positive?
                         repos[0].image_url
                       else
                         profile.github.user_profile['avatar_url']
                       end
  end

  def set_defaults
    return unless new_record?

    self.tagline ||= name
    self.description ||= ''
  end

  def add_repo(repo)
    prof_repo_analysis = repo.profile_repo_analyses.find_by!(profile: profile)
    profile_repo_analyses << prof_repo_analysis
    # update aggregated_tech_analysis
    aggregate_analysis
    repo.reload
  end

  def remove_repo(repo)
    prof_repo_analysis = repo.profile_repo_analyses.find_by!(profile: profile)
    prof_repo_analysis.update!(project: nil)
    # update aggregated_tech_analysis
    aggregate_analysis
    repo.reload
  end

  def start_repo_analysis(force: false)
    repos_hash = {}
    repos.each do |repo|
      # analyse if force is true or last analysis is more than a week old
      if force || repo.analysis.nil? || repo.analysis['fetched_at'].to_datetime < Time.now - 7.days
        repos_hash[repo.full_name] = { id: repo.id }
      end
    end

    return if repos_hash.empty?

    url = Rails.configuration.x.repos.repo_analysis_invocation_url

    response = Faraday.post(url) do |req|
      req.body = {
        repos: repos_hash,
        token: profile.github.access_token
      }.to_json
    end

    if response.success?
      response.body
    else
      raise "Repo analysis failed with status #{response.status}:" \
            " #{response.body}"
    end
  end

  def aggregate_analysis
    # initialize new hash, we'll fully recompute the overall analysis
    aggregated = { libs: {}, tags: {}, tech: {} }
    profile_repo_analyses.pluck(:tech_analysis).each do |tech_analysis|
      next if tech_analysis.blank?

      tech_analysis.symbolize_keys!
      # category is one of [:libs, :tech, :tags]
      tech_analysis.each do |category, category_stats|
        # specific_key is the id of the lib, tech or tag
        # e.g. it can be 'rb.rails' (as library) or 'framework' (as a tag)
        category_stats.each do |specific_key, stats|
          unless aggregated[category].key?(specific_key)
            aggregated[category][specific_key] =
              initial_stats_unit_for_tech_analysis
          end

          aggregated[category][specific_key][:insertions] += stats['insertions']
          aggregated[category][specific_key][:deletions] += stats['deletions']
        end
      end
    end

    self.aggregated_tech_analysis = aggregated
    save!

    aggregated_tech_analysis
  end

  def set_image(img_file)
    # NOTE: img_file must be an instance of ActionDispatch::Http::UploadedFile

    # check for file size
    raise('Image size must be less than 5 MB') if img_file.size > 5.megabyte

    # checks for width-height
    w, h = FastImage.size(img_file)

    unless image_width_range.include?(w)
      raise('Image width must be between 800 and 1980 pixels')
    end

    raise('Image width and height must be in the ratio 2:1') unless 2 * h == w

    # upload image to cloudinary
    begin
      response = Cloudinary::Uploader.upload(
        img_file.to_io,
        folder: "users/#{profile.user_id}/projects/",
        public_id: id
      )
      self.image_url = response.fetch('url')
      save!
    rescue CloudinaryException => e
      raise(e.message)
    rescue e
      warn("Unhandled exception #{e}")
      raise('Something went wrong. Please try again later')
    end
  end

  private

  def max_repos
    5
  end

  def image_width_range
    800...1_980
  end

  def validate_number_of_repos
    if repos.length > max_repos
      errors.add(:repos,
                 "Each project should contain no more than #{max_repos} repos")
    end
  end

  def validate_analysis_profiles_must_match_project_profile
    profile_repo_analyses.each do |pr_analysis|
      unless profile == pr_analysis.profile
        errors.add(:profile_repo_analyses,
                   "Profile on project doens't match profile on analysis for repo #{pr_analysis.repo.full_name}")
      end
    end
  end

  def initial_stats_unit_for_tech_analysis
    { insertions: 0, deletions: 0 }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout 'user'

  before_action do
    @profile = current_user.profile
    @selectable_repos = @profile.profile_repo_analyses.all.select do |pr|
      pr.project.nil?
    end.map(&:repo)
    @projects = @profile.projects
  end

  def index; end

  def new; end

  def show
    @project = @projects.friendly.find(params[:id])
  end

  def edit
    @project = @projects.friendly.find(params[:id])
  end

  def create
    create_params = project_params.merge(profile: current_user.profile)
    selected_repos = JSON.parse(create_params.delete(:repos))
    selected_repos = selected_repos.map do |repo|
      @profile.repos.find(repo.fetch('id'))
    end
    project_image = create_params.delete(:project_image)

    @project = Project.create(create_params)

    if @project.persisted?
      # do next two steps only if project was created successfully
      selected_repos.each { |repo| @project.add_repo(repo) }
      unless project_image.nil?
        begin
          @project.set_image(project_image)
        rescue StandardError => e
          redirect_to project_new_path, alert: e.message
          return
        end
      end
      redirect_to projects_home_path, notice: 'Project created successfully!'
    elsif @project.errors.key?(:profile)
      redirect_to project_new_path,
                  alert: 'Something went wrong.' \
                         ' Did you try to create more than 5 projects?'
    else
      redirect_to project_new_path,
                  alert: @project.errors.full_messages.join(', ')
    end
  end

  def update
    @project = @projects.friendly.find(params[:id])
    update_params = project_params
    selected_repos = JSON.parse(update_params.delete(:repos))
    selected_repos = selected_repos.map do |repo|
      @profile.repos.find(repo.fetch('id'))
    end
    project_image = update_params.delete(:project_image)

    if @project.update(update_params)
      @project.profile_repo_analyses.each do |pr_analysis|
        pr_analysis.update!(project: nil)
      end
      # @project.aggregate_analysis
      selected_repos.each do |repo|
        @project.add_repo(repo)
      end
      unless project_image.nil?
        begin
          @project.set_image(project_image)
        rescue StandardError => e
          redirect_to edit_project_path(@project), alert: e.message
          return
        end
      end
      redirect_to edit_project_path(@project), notice: 'Updated successfully!'
    else
      redirect_to edit_project_path(@project), alert: 'Something went wrong'
    end
  end

  def delete
    @project = @projects.friendly.find(params[:id])
    @project.destroy

    redirect_to projects_home_path,
                notice: "Project '#{@project.name}' was deleted!"
  end

  private

  def project_params
    params.require(:project).permit(:name, :tagline, :description,
                                    :repos, :project_image)
  end
end

app/views/projects/edit.html.erb
<div class="bg-white rounded-lg shadow px-5 py-6 sm:px-6">
  <div class="pb-5 border-b border-gray-200 sm:flex sm:items-center sm:justify-between">
    <a href="javascript:history.back()" class="text-base hover:bg-blue-50 p-2 px-3 rounded-md leading-6 font-medium text-blue-500 hover:text-blue-700">
      &lsaquo; Go Back
    </a>
  </div>
  <%= render partial: "form", locals: { form_model: @project, form_url: update_project_path(@project) } %>
</div>

app/views/projects/index.html.erb
<div class="bg-white rounded-lg shadow px-5 py-6 sm:px-6">
  <div class="pb-5 border-b border-gray-200 sm:flex sm:items-center sm:justify-between">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
      Projects
    </h3>
    <div class="mt-3 sm:mt-0 sm:ml-4">
      <a href="<%= project_new_path %>" class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-teal-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500">
        Create new project
      </a>
    </div>
  </div>
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="mt-5 shadow overflow-hidden sm:rounded-md">
    <ul class="divide-y divide-gray-200">
      <% @projects.each do |project| %>
        <li>
          <a href="<%= project_path(project) %>" class="block hover:bg-gray-50">
            <div class="px-4 py-4 flex items-center sm:px-6">
              <div class="min-w-0 flex-1 sm:flex sm:items-center sm:justify-between">
                <div class="truncate">
                  <div class="flex text-sm">
                    <p class="font-medium text-teal-600 truncate"><%= project.name %></p>
                  </div>
                  <div class="mt-2 flex">
                    <div class="flex items-center text-sm text-gray-500">
                      <!-- Heroicon name: solid/calendar -->
                      <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
                      <p>
                        <%= project.tagline %>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="ml-5 flex-shrink-0">
                <button type="button" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-teal-700 bg-teal-100 hover:bg-teal-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500">
                  View Details
                </button>
                <svg class="inline-flex h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                </svg>
              </div>
            </div>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/projects/new.html.erb
<div class="bg-white rounded-lg shadow px-5 py-6 sm:px-6">
  <div class="pb-5 border-b border-gray-200 sm:flex sm:items-center sm:justify-between mb-5">
    <a href="<%= blogs_path %>" class="text-base hover:bg-blue-50 p-2 px-3 rounded-md leading-6 font-medium text-blue-500 hover:text-blue-700">
      &lsaquo; Go Back
    </a>
  </div>
  <% if alert %>
    <div class="rounded-lg bg-red-50 text-white overflow-hidden shadow mb-4">
      <div class="p-5">
        <div class="flex">
          <div class="flex-shrink-0">
            <!-- Heroicon name: solid/information-circle -->
            <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="ml-3 flex-1 md:flex md:justify-between">
            <p class="text-sm text-red-700">
              <%= alert %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if notice %>
    <div class="rounded-lg bg-blue-50 text-white overflow-hidden shadow mb-4">
      <div class="p-5">
        <div class="flex">
          <div class="flex-shrink-0">
            <!-- Heroicon name: solid/information-circle -->
            <svg class="h-5 w-5 text-blue-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="ml-3 flex-1 md:flex md:justify-between">
            <p class="text-sm text-blue-700">
              <%= notice %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= render partial: "form", locals: { form_model: nil, form_url: project_create_path } %>
  <%= link_to 'Back', blogs_path %>
</div>

app/views/projects/show.html.erb
<div class="bg-white rounded-lg shadow px-5 py-6 sm:px-6">
  <div class="pb-5 border-b border-gray-200 sm:flex sm:items-center sm:justify-between">
    <a href="<%= projects_home_path %>" class="text-lg leading-6 font-medium text-gray-900">
      &lsaquo; Back to Projects
    </a>
    <div class="inline-flex md:space-x-4 mt-3 sm:mt-0 sm:ml-4">
      <a href="<%= edit_project_path(@project) %>" class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-teal-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-teal-500">
        Edit Project
      </a>
      <%= link_to(delete_project_path(@project), method: :delete) do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 text-sm rounded-md shadow-sm bg-red-600 text-white px-2 hover:bg-red-700" fill="currentColor" viewBox="0 0 16 16">
          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
          <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
        </svg>
      <% end %>
    </div>
  </div>
  <div class="max-w-2xl mx-auto">
    <dl>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Project Name
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @project.name %>
        </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Tagline
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @project.tagline %>
        </dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Description
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @project.description %>
        </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Repos
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 flex flex-col">
          <% @project.repos.each do |repo| %>
            <%= link_to(repo.full_name, "https://github.com/#{repo.full_name}", target: "_blank", class: "text-teal-600 hover:text-teal-800") %>
          <% end %>
        </dd>
      </div>
    </dl>
    <%= image_tag(@project.image_url, class: "w-full") %>
  </div>
</div>