config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :blogs do
    member do
      put 'publish'
    end
  end
  get  'home/index'
  get  'profiles/oauth/github',
       to: 'profiles/oauth_github#oauth_initiate'
  get  'profiles/oauth/github/callback',
       to: 'profiles/oauth_github#oauth_callback'

  post 'internal/api/initial_analysis',
       to: 'analysis_endpoints/receive_analysis#receive_initial_analysis'
  post 'internal/api/tech_analysis',
       to: 'analysis_endpoints/receive_analysis#add_tech_analysis_by_repo'
  post 'internal/api/tech_analysis/status',
       to: 'analysis_endpoints/receive_analysis#tech_analysis_status'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    invitations: 'users/invitations',
    registrations: 'users/registrations'
  }, skip: [:registrations]

  as :user do
    put 'users' => 'users/registrations#update', :as => 'user_registration'
    delete 'users' => 'users/registrations#destroy', :as => 'user_delete'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  # Each step is further described in the setup controller
  scope '/setup' do
    get '/', to: 'setup#index', as: 'setup'
    get '/1', to: 'setup#step_one', as: 'setup_step_one'
    get '/2', to: 'setup#step_two', as: 'setup_step_two'
    get '/3', to: 'setup#step_three', as: 'setup_step_three'
    get '/4', to: 'setup#step_four', as: 'setup_step_four'

    post '/1', to: 'setup#step_one_submit', as: 'setup_step_one_submit'
    post '/2', to: 'setup#step_two_submit', as: 'setup_step_two_submit'
    post '/3', to: 'setup#step_three_submit', as: 'setup_step_three_submit'
    post '/4', to: 'setup#step_four_submit', as: 'setup_step_four_submit'

    post '/previous_step', to: 'setup#previous_step', as: 'setup_previous_step'
  end

  scope '/internal/api' do
    post 'initial_analysis',
         to: 'analysis_endpoints/receive_analysis#receive_initial_analysis'
    post 'tech_analysis',
         to: 'analysis_endpoints/receive_analysis#add_tech_analysis_by_repo'
    post 'repo_analysis',
         to: 'analysis_endpoints/receive_analysis#repo_analysis'
  end

  scope '/data_api' do
    get '/user_info', to: 'data_api#user_info'
    get '/user_socials', to: 'data_api#user_socials'
    get '/projects', to: 'data_api#projects'
    get '/projects/:id', to: 'data_api#project_info'
    get '/projects/:project_id/repos/:repo_id', to: 'data_api#project_repo'
    get '/blogs', to: 'data_api#blogs'
    get '/blogs/:id', to: 'data_api#blog_info'
  end

  scope '/settings' do
    get '/profile', to: 'settings#profile'
    put '/profile', to: 'settings#profile_edit'
    put '/profile_social', to: 'settings#social_edit'
    put '/profile_contact_info', to: 'settings#contact_info_edit'
    get '/themes', to: 'settings#themes'
    put '/themes', to: 'settings#themes_edit'
    get '/account', to: 'settings#account'
    get '/password', to: 'settings#password'
  end

  scope '/projects' do
    get '/', to: 'projects#index', as: 'projects_home'
    get '/new', to: 'projects#new', as: 'project_new'
    put '/new', to: 'projects#create', as: 'project_create'
    get '/:id', to: 'projects#show', as: 'project'
    put '/:id', to: 'projects#update', as: 'update_project'
    get '/:id/edit', to: 'projects#edit', as: 'edit_project'
    delete '/:id', to: 'projects#delete', as: 'delete_project'
  end
end

app/controllers/setup_controller.rb
# This file contains 4 steps for the user.
#
# Step one: Connect with Github
# Step Two: Enter user information
# Step Three: Enter about field data
# Step four: Select a theme
#
# Upon Successfully completing everything, user would be redirected to the
# projects page.
class SetupController < ApplicationController
  layout 'setup'

  def index
    if current_user.setup_step.positive?
      redirect_to("/setup/#{current_user.setup_step}")
    else
      redirect_to '/', alert: 'Setup Already Completed'
    end
  end

  def step_one
    if current_user.setup_step != 1
      redirect_to("/setup/#{current_user.setup_step}")
    end
  end

  def step_two
    if current_user.setup_step != 2
      redirect_to("/setup/#{current_user.setup_step}")
    end
    @base_social_links = Profile.base_social_links
    @social_links = current_user.profile.social_links.symbolize_keys
    @user = current_user
  end

  def step_three
    if current_user.setup_step != 3
      redirect_to("/setup/#{current_user.setup_step}")
    end
    @contact_info = current_user.profile.contact_info
    @user = current_user
  end

  def step_four
    if current_user.setup_step != 4
      redirect_to("/setup/#{current_user.setup_step}")
    end
    @valid_themes = Profile.valid_themes
    @current_theme = current_user.profile.theme
  end

  def step_one_submit
    current_user.setup_step = 2
    current_user.save
    redirect_to("/setup/#{current_user.setup_step}")
  end

  def step_two_submit
    profile = current_user.profile

    if profile.update!(social_params)
      current_user.setup_step = 3
      current_user.save
      redirect_to("/setup/#{current_user.setup_step}",
                  notice: 'Social Profiles Added Successfully')
    else
      redirect_to("/setup/#{current_user.setup_step}",
                  alert: 'Something went wrong. Please try again.')
    end
  end

  def step_three_submit
    profile = current_user.profile

    params_object = contact_info_params

    if params_object.dig('contact_info', 'phone')
      phone = Phonelib.parse(params_object.dig('contact_info', 'phone'))
      params_object[:contact_info][:phone] =
        if phone.country_code
          phone.international
        else
          phone.e164
        end
    end

    if profile.update(params_object)
      current_user.setup_step = 4
      current_user.save
      redirect_to "/setup/#{current_user.setup_step}",
                  notice: 'Contact Info Added'
    else
      redirect_to "/setup/#{current_user.setup_step}",
                  alert: profile.errors.full_messages.to_sentence
    end
  end

  def step_four_submit
    profile = current_user.profile
    theme = Theme.find(theme_params[:theme])
    if profile.update(theme: theme)
      profile.start_theme_build
      current_user.setup_step = 0
      current_user.save
      redirect_to('/projects', notice: 'Setup Completed Successfully!')
    else
      redirect_to "/setup/#{current_user.setup_step}",
                  alert: profile.errors.full_messages.to_sentence
    end
  end

  def previous_step
    current_user.setup_step -= 1
    current_user.save
    redirect_to("/setup/#{current_user.setup_step}")
  end

  private

  def social_params
    params.require(:profile).permit(:tagline,
                                    social_links: Profile.valid_socials)
  end

  def contact_info_params
    params.require(:profile).permit(contact_info: %i[email phone location])
  end

  def theme_params
    params.require(:theme).permit(:theme)
  end
end

app/views/setup/_steps.html.erb
<nav aria-label="Progress" class="flex justify-center">
  <ol class="flex items-center">
    <% 4.times do |i| %>
      <li class="relative<% if i+1 != 4 %> pr-8 sm:pr-20<% end %>">
        <div class="absolute inset-0 flex items-center" aria-hidden="true">
          <% if current_user.setup_step > i+1 %>
            <div class="h-0.5 w-full bg-teal-600"></div>
          <% else %>
            <div class="h-0.5 w-full bg-gray-200"></div>
          <% end %>
        </div>
        <% if current_user.setup_step > i+1 %>
          <!-- Completed Step -->
          <a class="relative w-8 h-8 flex items-center justify-center bg-teal-600 rounded-full hover:bg-teal-900">
            <!-- Heroicon name: solid/check -->
            <svg class="w-5 h-5 text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
            </svg>
            <span class="sr-only">Step <%= i+1 %></span>
          </a>
        <% elsif current_user.setup_step == i+1 %>
          <a class="relative w-8 h-8 flex items-center justify-center bg-white border-2 border-teal-600 rounded-full" aria-current="step">
            <span class="h-2.5 w-2.5 bg-teal-600 rounded-full" aria-hidden="true"></span>
            <span class="sr-only">Step <%= i+1 %></span>
          </a>
        <% else %>
          <a class="group relative w-8 h-8 flex items-center justify-center bg-white border-2 border-gray-300 rounded-full hover:border-gray-400">
            <span class="h-2.5 w-2.5 bg-transparent rounded-full group-hover:bg-gray-300" aria-hidden="true"></span>
            <span class="sr-only">Step <%= i+1 %></span>
          </a>
        <% end %>
      </li>
    <% end %>
  </ol>
</nav>

app/views/setup/step_four.html.erb
<%= render "steps" %>
<div class="mt-10" x-data="{selected: <%= @current_theme.id %>}">
  <%= form_with url: setup_step_four_submit_path, method: :post, scope: :theme do |f| %>
    <ul class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
      <% @valid_themes.each do |theme| %>
        <!-- Selected Class: "col-span-1 bg-teal-50 rounded-lg shadow divide-y divide-gray-200 ring ring-teal-300 cursor-pointer" -->
        <li @click="selected = <%= theme.id %>" :class="selected === <%= theme.id %> ? 'bg-teal-50 ring ring-teal-300' : 'bg-white'" class="col-span-1 bg-white rounded-lg shadow divide-y divide-gray-200 cursor-pointer transform duration-150 ease-in-out">
          <div class="flex w-full flex-col">
            <img class="rounded-t-lg " src="https://via.placeholder.com/300x150" alt="<%= theme.name %>">
            <div class="flex px-5 py-2 items-center">
              <!-- Selected Class: "font-medium px-5 py-3" -->
              <span class="flex-1"><%= theme.name %></span>
              <%= link_to('Preview', theme.preview_url || '#', target: "_blank", rel: "noopener noreferrer", class: "inline-flex flex-2 items-center px-2.5 h-8 border border-transparent text-xs font-medium rounded text-blue-700 bg-blue-100 hover:bg-blue-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500") %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
    <input type="hidden" name="theme[theme]" x-bind:value="selected">
    <div class="pt-5">
      <div class="flex justify-between">
        <%= link_to "Previous", setup_previous_step_path, method: :pose, class: "ml-3 inline-flex justify-center py-2 px-4 border border-gray-400 shadow-sm text-sm font-medium rounded-md text-gray-600 bg-white hover:bg-gray-200 cursor-pointer focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
        <%= f.submit "Complete Setup", class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-teal-600 hover:bg-teal-700 focus:outline-none focus:ring-2 cursor-pointer focus:ring-offset-2 focus:ring-teal-500" %>
      </div>
    </div>
  <% end %>
</div>

app/views/setup/step_one.html.erb
<%= render "steps" %>
<% if !current_user.profile.github %>
  <div>
    <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full">
      <svg class="w-8 h-8 mr-2" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
        <path fill-rule="evenodd" d="M10 0C4.477 0 0 4.484 0 10.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0110 4.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.203 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.942.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0020 10.017C20 4.484 15.522 0 10 0z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="mt-1 text-center sm:mt-5">
      <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-headline">
        Let's start analysing!
      </h3>
      <div class="mt-2">
        <p class="text-sm text-gray-500">
          We just need you to connect your GitHub profile here. We'll start analysing your profile immediately.
        </p>
      </div>
    </div>
  </div>
  <div class="mt-5 flex justify-center sm:mt-6">
    <div class="relative inline-flex rounded-md shadow-sm">
      <%= button_to profiles_oauth_github_path, method: :get, form: {"data-turbo" => "false"}, class: "w-full inline-flex justify-center py-2 px-4 border border-gray-300 rounded-md shadow-sm bg-white text-sm font-medium text-gray-500 hover:bg-gray-50" do %>
        <span class="sr-only">Connect with GitHub</span>
        <svg class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 0C4.477 0 0 4.484 0 10.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0110 4.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.203 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.942.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0020 10.017C20 4.484 15.522 0 10 0z" clip-rule="evenodd" />
        </svg> Connect with GitHub
      <% end %>
      <span class="flex absolute h-3 w-3 top-0 right-0 -mt-1 -mr-1">
        <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-teal-400 opacity-75"></span>
        <span class="relative inline-flex rounded-full h-3 w-3 bg-teal-500"></span>
      </span>
    </div>
  </div>
<% else %>
  <div class="flex flex-col justify-center mt-10">
    <div class="prose prose-lg">
      <span class="bg-gradient-to-r from-teal-200 to-green-200 text-gray-600 p-1 font-semibold">Great Job 🎉! Your GitHub profile is successfully connected for further analysis.</span><br /> We'll let you know when we completely analyse your profile. Let's continue with our setup, shall we?
    </div>
  </div>
<% end %>

<div class="pt-5">
  <div class="flex justify-end">
    <%= button_to "Next", setup_step_one_submit_path, method: :post, class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-teal-600 hover:bg-teal-700 focus:outline-none focus:ring-2 cursor-pointer focus:ring-offset-2 focus:ring-teal-500" %>
  </div>
</div>

app/views/setup/step_three.html.erb
<%= render "steps" %>
<%= form_with model: @user.profile, url: setup_step_three_submit_path, html: { method: :post, class: "flex-grow space-y-4 max-w-2xl mx-auto" } do |f| %>
  <div class="mt-6 grid grid-cols-12 gap-6">
    <div class="col-span-12">
      <%= f.label 'contact_info[email]', 'Email Address', class: "block text-sm font-medium text-gray-700" %>
      <%= f.email_field 'contact_info[email]', value: @contact_info.fetch('email'), placeholder: 'yourname@example.com', class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm" %>
    </div>
    <div class="col-span-12">
      <%= f.label 'contact_info[phone]', 'Phone Number', class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field 'contact_info[phone]', value: @contact_info.fetch('phone'), placeholder: 'Prefer adding your country code (e.g. +1 for US, +91 for India)', class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm" %>
    </div>
    <div class="col-span-12">
      <%= f.label 'contact_info[location]', 'Location', class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field 'contact_info[location]', value: @contact_info.fetch('location'), placeholder: 'Geek City, Developer Heaven.', class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm" %>
    </div>
  </div>
  <div class="pt-5">
    <div class="flex justify-between">
      <%= link_to "Previous", setup_previous_step_path, method: :pose, class: "ml-3 inline-flex justify-center py-2 px-4 border border-gray-400 shadow-sm text-sm font-medium rounded-md text-gray-600 bg-white hover:bg-gray-200 cursor-pointer focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
      <%= f.submit "Next", class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-teal-600 hover:bg-teal-700 focus:outline-none focus:ring-2 cursor-pointer focus:ring-offset-2 focus:ring-teal-500" %>
    </div>
  </div>
<% end %>

app/views/setup/step_two.html.erb
<%= render "steps" %>
<%= form_with model: @user.profile, url: setup_step_two_submit_path, html: { method: :post, class: "flex-grow space-y-4 mt-5 max-w-2xl mx-auto" } do |f| %>
  <div class="bg-white">
    <div>
      <%= f.label :tagline, class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field :tagline, value: current_user.profile.tagline, placeholder: "Developer by day, Batman by night", class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm"%>
    </div>
    <br />
    <div class="grid grid-cols-6 gap-6">
      <div class="col-span-6 sm:col-span-3">
        <%= f.label 'social_links[linkedin]', 'LinkedIn', class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1 flex rounded-md shadow-sm">
          <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
            <%= @base_social_links[:linkedin] %>
          </span>
          <%= f.text_field 'social_links[linkedin]', value: @social_links.fetch(:linkedin, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
        </div>
      </div>
      <div class="col-span-6 sm:col-span-3">
        <%= f.label 'social_links[devto]', 'Dev.to', class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1 flex rounded-md shadow-sm">
          <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
            <%= @base_social_links[:devto] %>
          </span>
          <%= f.text_field 'social_links[devto]', value: @social_links.fetch(:devto, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
        </div>
      </div>
      <div class="col-span-6 sm:col-span-3">
        <%= f.label 'social_links[stackoverflow]', 'Stack Overflow', class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1 flex rounded-md shadow-sm">
          <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
            <%= @base_social_links[:stackoverflow] %>
          </span>
          <%= f.text_field 'social_links[stackoverflow]', value: @social_links.fetch(:stackoverflow, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "User Number"%>
        </div>
      </div>
      <div class="col-span-6 sm:col-span-3">
        <%= f.label 'social_links[dribbble]', 'Dribbble', class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1 flex rounded-md shadow-sm">
          <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
            <%= @base_social_links[:dribbble] %>
          </span>
          <%= f.text_field 'social_links[dribbble]', value: @social_links.fetch(:dribbble, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
        </div>
      </div>
      <div class="col-span-6 sm:col-span-3">
        <%= f.label 'social_links[facebook]', 'Facebook', class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1 flex rounded-md shadow-sm">
          <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
            <%= @base_social_links[:facebook] %>
          </span>
          <%= f.text_field 'social_links[facebook]', value: @social_links.fetch(:facebook, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
        </div>
      </div>
      <div class="col-span-6 sm:col-span-3">
        <%= f.label 'social_links[twitter]', 'Twitter', class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1 flex rounded-md shadow-sm">
          <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
            <%= @base_social_links[:twitter] %>
          </span>
          <%= f.text_field 'social_links[twitter]', value: @social_links.fetch(:twitter, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
        </div>
      </div>
      <div class="col-span-6 sm:col-span-3">
        <%= f.label 'social_links[github]', 'GitHub', class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1 flex rounded-md shadow-sm">
          <span class="bg-gray-50 border border-gray-300 rounded-l-md px-3 inline-flex items-center text-gray-500 sm:text-sm">
            <%= @base_social_links[:github] %>
          </span>
          <%= f.text_field 'social_links[github]', value: @social_links.fetch(:github, ''), class: "focus:ring-teal-500 focus:border-teal-500 flex-grow block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder: "Username"%>
        </div>
      </div>
    </div>
  </div>
  <div class="pt-5">
    <div class="flex justify-between">
      <%= link_to "Previous", setup_previous_step_path, method: :pose, class: "ml-3 inline-flex justify-center py-2 px-4 border border-gray-400 shadow-sm text-sm font-medium rounded-md text-gray-600 bg-white hover:bg-gray-200 cursor-pointer focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
      <%= f.submit "Next", class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-teal-600 hover:bg-teal-700 focus:outline-none focus:ring-2 cursor-pointer focus:ring-offset-2 focus:ring-teal-500" %>
    </div>
  </div>
<% end %>