config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :blogs do
    member do
      put 'publish'
    end
  end
  get  'home/index'
  get  'profiles/oauth/github',
       to: 'profiles/oauth_github#oauth_initiate'
  get  'profiles/oauth/github/callback',
       to: 'profiles/oauth_github#oauth_callback'

  post 'internal/api/initial_analysis',
       to: 'analysis_endpoints/receive_analysis#receive_initial_analysis'
  post 'internal/api/tech_analysis',
       to: 'analysis_endpoints/receive_analysis#add_tech_analysis_by_repo'
  post 'internal/api/tech_analysis/status',
       to: 'analysis_endpoints/receive_analysis#tech_analysis_status'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    invitations: 'users/invitations',
    registrations: 'users/registrations'
  }, skip: [:registrations]

  as :user do
    put 'users' => 'users/registrations#update', :as => 'user_registration'
    delete 'users' => 'users/registrations#destroy', :as => 'user_delete'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  # Each step is further described in the setup controller
  scope '/setup' do
    get '/', to: 'setup#index', as: 'setup'
    get '/1', to: 'setup#step_one', as: 'setup_step_one'
    get '/2', to: 'setup#step_two', as: 'setup_step_two'
    get '/3', to: 'setup#step_three', as: 'setup_step_three'
    get '/4', to: 'setup#step_four', as: 'setup_step_four'

    post '/1', to: 'setup#step_one_submit', as: 'setup_step_one_submit'
    post '/2', to: 'setup#step_two_submit', as: 'setup_step_two_submit'
    post '/3', to: 'setup#step_three_submit', as: 'setup_step_three_submit'
    post '/4', to: 'setup#step_four_submit', as: 'setup_step_four_submit'

    post '/previous_step', to: 'setup#previous_step', as: 'setup_previous_step'
  end

  scope '/internal/api' do
    post 'initial_analysis',
         to: 'analysis_endpoints/receive_analysis#receive_initial_analysis'
    post 'tech_analysis',
         to: 'analysis_endpoints/receive_analysis#add_tech_analysis_by_repo'
    post 'repo_analysis',
         to: 'analysis_endpoints/receive_analysis#repo_analysis'
  end

  scope '/data_api' do
    get '/user_info', to: 'data_api#user_info'
    get '/user_socials', to: 'data_api#user_socials'
    get '/projects', to: 'data_api#projects'
    get '/projects/:id', to: 'data_api#project_info'
    get '/projects/:project_id/repos/:repo_id', to: 'data_api#project_repo'
    get '/blogs', to: 'data_api#blogs'
    get '/blogs/:id', to: 'data_api#blog_info'
  end

  scope '/settings' do
    get '/profile', to: 'settings#profile'
    put '/profile', to: 'settings#profile_edit'
    put '/profile_social', to: 'settings#social_edit'
    put '/profile_contact_info', to: 'settings#contact_info_edit'
    get '/themes', to: 'settings#themes'
    put '/themes', to: 'settings#themes_edit'
    get '/account', to: 'settings#account'
    get '/password', to: 'settings#password'
  end

  scope '/projects' do
    get '/', to: 'projects#index', as: 'projects_home'
    get '/new', to: 'projects#new', as: 'project_new'
    put '/new', to: 'projects#create', as: 'project_create'
    get '/:id', to: 'projects#show', as: 'project'
    put '/:id', to: 'projects#update', as: 'update_project'
    get '/:id/edit', to: 'projects#edit', as: 'edit_project'
    delete '/:id', to: 'projects#delete', as: 'delete_project'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hyperlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/settings.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hyperlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
    <%= stylesheet_link_tag 'application', media: 'all' , 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' , 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="min-h-screen bg-gray-100">
      <%= render "layouts/navigation" %>
      <main class="-mt-24 pb-8">
        <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">
          <h1 class="sr-only">Settings</h1>
          <main class="relative">
            <h1 class="mb-3 text-3xl text-white font-bold">Settings</div>
            <div class="max-w-screen-xl mx-auto pb-6 px-4 sm:px-6 lg:pb-16 lg:px-8">
              <div class="bg-white rounded-lg shadow overflow-hidden">
                <div class="divide-y divide-gray-200 lg:grid lg:grid-cols-12 lg:divide-y-0 lg:divide-x">
                  <aside class="py-6 lg:col-span-3">
                    <nav>
                      <!-- Current: "bg-teal-50 border-teal-500 text-teal-700 hover:bg-teal-50 hover:text-teal-700", Default: "border-transparent text-gray-900 hover:bg-gray-50 hover:text-gray-900" -->
                      <a href="<%= profile_path %>" class="<%= current_page?(profile_path) ? "bg-teal-50 border-teal-500 text-teal-700 hover:bg-teal-50 hover:text-teal-700" : "border-transparent text-gray-900 hover:bg-gray-50 hover:text-gray-900" %> group border-l-4 px-3 py-2 flex items-center text-sm font-medium" aria-current="page">
                        <!-- Current: "text-teal-500 group-hover:text-teal-500", Default: "text-gray-400 group-hover:text-gray-500" -->
                        <!-- Heroicon name: outline/user-circle -->
                        <svg class="<%= current_page?(profile_path) ? "text-teal-500 group-hover:text-teal-500" : "text-gray-400 group-hover:text-gray-500" %> flex-shrink-0 -ml-1 mr-3 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        <span class="truncate">
                          Profile
                        </span>
                      </a>
                      <a href="<%= account_path %>" class="<%= current_page?(account_path) ? "bg-teal-50 border-teal-500 text-teal-700 hover:bg-teal-50 hover:text-teal-700" : "border-transparent text-gray-900 hover:bg-gray-50 hover:text-gray-900" %> group border-l-4 px-3 py-2 flex items-center text-sm font-medium" aria-current="page">
                        <!-- Heroicon name: outline/cog -->
                        <svg class="<%= current_page?(account_path) ? "text-teal-500 group-hover:text-teal-500" : "text-gray-400 group-hover:text-gray-500" %> flex-shrink-0 -ml-1 mr-3 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>
                        <span class="truncate">
                          Account
                        </span>
                      </a>
                      <a href="<%= password_path %>" class="<%= current_page?(password_path) ? "bg-teal-50 border-teal-500 text-teal-700 hover:bg-teal-50 hover:text-teal-700" : "border-transparent text-gray-900 hover:bg-gray-50 hover:text-gray-900" %> group border-l-4 px-3 py-2 flex items-center text-sm font-medium" aria-current="page">
                        <!-- Heroicon name: outline/key -->
                        <svg class="<%= current_page?(password_path) ? "text-teal-500 group-hover:text-teal-500" : "text-gray-400 group-hover:text-gray-500" %> flex-shrink-0 -ml-1 mr-3 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
                        </svg>
                        <span class="truncate">
                          Password
                        </span>
                      </a>
                      <a href="<%= themes_path %>" class="<%= current_page?(themes_path) ? "bg-teal-50 border-teal-500 text-teal-700 hover:bg-teal-50 hover:text-teal-700" : "border-transparent text-gray-900 hover:bg-gray-50 hover:text-gray-900" %> group border-l-4 px-3 py-2 flex items-center text-sm font-medium" aria-current="page">
                        <!-- Heroicon name: outline/bell -->
                        <svg class="<%= current_page?(themes_path) ? "text-teal-500 group-hover:text-teal-500" : "text-gray-400 group-hover:text-gray-500" %> flex-shrink-0 -ml-1 mr-3 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                        </svg>
                        <span class="truncate">
                          Themes
                        </span>
                      </a>
                    </nav>
                  </aside>
                  <div class="divide-y divide-gray-200 lg:col-span-9">
                    <div class="py-6 px-4 sm:p-6 lg:pb-8">
                      <% if alert %>
                        <div class="rounded-lg bg-red-50 text-white overflow-hidden shadow mb-6">
                          <div class="p-5">
                            <div class="flex">
                              <div class="flex-shrink-0">
                                <!-- Heroicon name: solid/information-circle -->
                                <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                  <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
                                </svg>
                              </div>
                              <div class="ml-3 flex-1 md:flex md:justify-between">
                                <p class="text-sm text-red-700">
                                  <%= alert %>
                                </p>
                              </div>
                            </div>
                          </div>
                        </div>
                      <% end %>
                      <% if notice %>
                        <div class="rounded-lg bg-blue-50 text-white overflow-hidden shadow mb-6">
                          <div class="p-5">
                            <div class="flex">
                              <div class="flex-shrink-0">
                                <!-- Heroicon name: solid/information-circle -->
                                <svg class="h-5 w-5 text-blue-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                  <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
                                </svg>
                              </div>
                              <div class="ml-3 flex-1 md:flex md:justify-between">
                                <p class="text-sm text-blue-700">
                                  <%= notice %>
                                </p>
                              </div>
                            </div>
                          </div>
                        </div>
                      <% end %>
                      <%= yield %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </main>
        </div>
      </main>
      <footer>
        <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 lg:max-w-7xl">
          <div class="border-t border-gray-200 py-8 text-sm text-gray-500 text-center sm:text-left"><span
            class="block sm:inline">&copy; 2021 Hyperlog Pvt Ltd.</span> <span class="block sm:inline">All rights
              reserved.</span></div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/setup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hyperlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
    <%= stylesheet_link_tag 'application', media: 'all' , 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' , 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body {
        background: linear-gradient(-45deg, #0D9488, #14B8A6, #0D9488, #14B8A6);
        background-size: 400% 400%;
        animation: gradient 15s ease infinite;
      }
      
      @keyframes gradient {
        0% {
          background-position: 0% 50%;
        }
        50% {
          background-position: 100% 50%;
        }
        100% {
          background-position: 0% 50%;
        }
      }
    </style>
  </head>
  <body>
    <div class="bg-scroll min-h-screen">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="max-w-3xl mx-auto">
          <div class="flex">
            <%= image_tag "logo-white.svg", class: "my-10 w-16 h-16 m-auto" %>
          </div>
          <div class="bg-white overflow-hidden shadow rounded-lg mb-10">
            <div class="px-4 py-5 sm:p-6">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hyperlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
    <%= stylesheet_link_tag 'application', media: 'all' , 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' , 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="min-h-screen bg-gray-100">
      <%= render "layouts/navigation" %>
      <main class="-mt-24 pb-8">
        <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">
          <h1 class="sr-only">Page title</h1>
          <%= yield %>
        </div>
      </main>
      <footer>
        <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 lg:max-w-7xl">
          <div class="border-t border-gray-200 py-8 text-sm text-gray-500 text-center sm:text-left"><span
            class="block sm:inline">&copy; 2021 Hyperlog Pvt Ltd.</span> <span class="block sm:inline">All rights
              reserved.</span></div>
        </div>
      </footer>
    </div>
  </body>
</html>